Update seraphscript

diff --git a/seraphscript b/seraphscript
--- a/seraphscript
+++ b/seraphscript
@@ -1,6 +1,8 @@
 # SERAPH
 #!/bin/bash
 cd ..
+# Check for systemd
+systemctl --version >/dev/null 2>&1 || { echo "systemd is required. Are you using Ubuntu 16.04?"  >&2; exit 1; }
 echo && sleep 3
 read -e -p "Add swap space? (Recommended) [Y/n] : " add_swap
 if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
