Update seraphscript

diff --git a/seraphscript b/seraphscript
--- a/seraphscript
+++ b/seraphscript
@@ -2,6 +2,11 @@
 #!/bin/bash
 cd ..
 
+RED='\033[0;91m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+NC='\033[0m' # No Color
+
 # Gather input from user
 read -e -p "Masternode Private Key (e.g. 5FBze4taSwYNkAWQAurPn6rBi7VeisdejYq9JQchHuRzHDuCYZG) : " key
 if [[ "$key" == "" ]]; then
@@ -9,6 +14,22 @@ if [[ "$key" == "" ]]; then
     echo && exit
 fi
 sleep 3
+
+dpkg -s dnsutils 2>/dev/null >/dev/null || sudo apt-get -y install dnsutils
+publicip=$(dig +short myip.opendns.com @resolver1.opendns.com)
+
+if [ -n "$publicip" ]; then
+    echo -e "${YELLOW}IP Address detected:" $publicip ${NC}
+else
+    echo -e "${RED}ERROR:${YELLOW} Public IP Address was not detected!${NC} \a"
+    clear_stdin
+    read -e -p "Enter VPS Public IP Address: " publicip
+    if [ -z "$publicip" ]; then
+        echo -e "${RED}ERROR:${YELLOW} Public IP Address must be provided. Try again...${NC} \a"
+        exit 1
+    fi
+fi
+echo && sleep 3
 
 read -e -p "Add swap space? (Recommended) [Y/n] : " add_swap
 if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
@@ -61,10 +82,10 @@ sleep 10
 
 rpcuser=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
 rpcpassword=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
-externalip=$(curl -s ipv4bot.whatismyipaddress.com)
+#externalip=$(curl -s ipv4bot.whatismyipaddress.com)
 #masternodekey=$(./seraph-cli masternode genkey)
 ./seraph-cli stop
-echo -e "rpcuser=$rpcuser\nrpcpassword=$rpcpassword\nrpcallowip=127.0.0.1\nlisten=1\nserver=1\ndaemon=1\nrpcport=25674\nstaking=0\nexternalip=$externalip:25676\nmaxconnections=256\nmasternode=1\nmasternodeprivkey=$key" >> $HOME/.seraph/seraph.conf
+echo -e "rpcuser=$rpcuser\nrpcpassword=$rpcpassword\nrpcallowip=127.0.0.1\nlisten=1\nserver=1\ndaemon=1\nrpcport=25674\nstaking=0\nexternalip=$publicip:25676\nmaxconnections=256\nmasternode=1\nmasternodeprivkey=$key" >> $HOME/.seraph/seraph.conf
 echo "Masternode private key: $key"
 ./seraphd -daemon
 
